define([], function () {
  return {
    "PropertyPaneDescription": "Manage web hook subscriptions on the lists in this site",
    "BasicGroupName": "Basic Settings",
    "DatePickerStrings": {
      "months": [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
      ],
      "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      "days": ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      "shortDays": ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      "goToToday": 'Go to today',
      "prevMonthAriaLabel": 'Go to previous month',
      "nextMonthAriaLabel": 'Go to next month',
      "prevYearAriaLabel": 'Go to previous year',
      "nextYearAriaLabel": 'Go to next year'
    },
    "DeleteErrorTitle": "Delete Subscription Error",
    "AddErrorTitle": "Add Subscription Error",
    "UpdateErrorTitle": "Update Subscription Error",
    "Loading": "Loading...",
    "EditSubscription": "Edit Subscription",
    "DeleteSubscription": "Delete Subscription",
    "EmptyTextField": "N/A",
    "ConfirmDelete": "Are you sure you want to delete this subscription?",
    "DeletingSubscription": "Deleting subscription...",
    "HideSubscriptions": "Hide Subscriptions",
    "ExpandSubscriptions": "Expand Subscriptions",
    "AddSubscription": "Add Subscription",
    "NoSubscriptions": "No subscriptions",
    "UpdatingSubscription": "Updating subscription...",
    "SelectDate": "Select a date...",
    "ExpirationDate": "Expiration Date",
    "AddMaxExpiration": "Add Max Expiration",
    "ID": "ID",
    "ClientState": "Client State",
    "Resource": "Resource",
    "NotificationUrl": "Notification URL",
    "OK": "OK",
    "Cancel": "Cancel",
    "AddingSubscription": "Adding new subscription...",
    "Save": "Save",
    "NotificationUrlError": "Please enter a valid notification url",
    "ErrorUpdatingMessage": "An error updating your subscription has occurred.",
    "ErrorAddingMessage": "An error adding your new subscription has occurred.",
    "ErrorDeletingMessage": "An error deleting your subscription has occurred.",
    "ErrorFetchingSubscriptions": "There was an error fetching the web hook subscriptions",
    "Subscription": "Subscription",
    "SelectQueryType": "Select query type",
    "List": "List",
    "Template": "Template",
    "SelectList": "Select a list",
    "ListTemplateTypes": "List Template Types"
  }
});
