export enum SubscriptionActionTypes {
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  APPLY_PROPERTIES = 'APPLY_PROPERTIES',
  GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_ERROR = 'GET_SUBSCRIPTIONS_ERROR'
}

export enum AddSubscriptionActionTypes {
  UPDATE_NEW_PROPERTY = 'UPDATE_NEW_PROPERTY',
  ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS',
  ADD_SUBSCRIPTION_ERROR = 'ADD_SUBSCRIPTION_ERROR',
  SHOW_ADD_PANEL = 'SHOW_ADD_PANEL',
  RESET_ADD_SUBSCRIPTION = 'RESET_ADD_SUBSCRIPTION'
}
