export enum SubscriptionActionTypes {
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  APPLY_PROPERTIES = 'APPLY_PROPERTIES',
  GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_ERROR = 'GET_SUBSCRIPTIONS_ERROR'
}

export enum AddSubscriptionActionTypes {
  UPDATE_NEW_PROPERTY = 'UPDATE_NEW_PROPERTY'
}
